- src/lib.rs
Since linux-raw-sys uses ctypes types in its public APIs, re-export
ctypes so that users can use it directly instead of having to redo
the no-std incantations.
> Re-export ctypes.

- Cargo.toml
- gen/src/main.rs
- src/lib.rs
In `no_std` builds, define `ctypes` types manually instead of depending
on the `cty` crate. These types are straightforward to define for all
Linux targets.
> Define `ctypes` manually instead of depending on `cty`.

- gen/modules/general.h
Code in general.h should contain just what's needed for interoperability
with the Linux kernel ABI. Add a comment explaining this, and tidy up
a few parts of the code to follow this advice.
> Document the purpose of the code in gen/modules/general.h.

- Cargo.toml
The .github, .rustfmt.toml, and .gitignore files aren't needed by
downstream users of the crate, so exclude them from the published
package.
> Exclude the `.github` directory in the published package.

- Cargo.toml
Avoid enabling the rustc-dep-of-std feature in the docs.rs build, as it
replaces core, which breaks rustdoc.
> Fix the docs.rs build.

- .gitignore
- src/lib.rs
This PR adds CMSG macros based off of the ones found [here](https://github.com/torvalds/linux/blob/f86d1fbbe7858884d6754534a0afbb74fc30bc26/include/linux/socket.h#L107-L135). I want to add `sendmsg`/`recvmsg` to Rustix, but I'd rather not deduplicate these functions there.
> Add CMSG macros

- gen/modules/general.h
- src/aarch64/general.rs
- src/arm/general.rs
- src/mips/general.rs
- src/mips64/general.rs
- src/powerpc/general.rs
- src/powerpc64/general.rs
- src/riscv32/general.rs
- src/riscv64/general.rs
- src/s390x/general.rs
- src/sparc/general.rs
- src/sparc64/general.rs
- src/x32/general.rs
- src/x86/general.rs
- src/x86_64/general.rs
This includes the `CAP_*` constants.
Fixes #41.
> Add <linux/capabilith.h> to the general module.

- gen/modules/general.h
- src/aarch64/general.rs
- src/arm/general.rs
- src/mips/general.rs
- src/mips64/general.rs
- src/powerpc/general.rs
- src/powerpc64/general.rs
- src/riscv32/general.rs
- src/riscv64/general.rs
- src/s390x/general.rs
- src/sparc/general.rs
- src/sparc64/general.rs
- src/x32/general.rs
- src/x86/general.rs
- src/x86_64/general.rs
See the comments in gen/modules/general.h for details, but in short, the definitions of `NSIG`, `sigset_t`, and `sigaction` provided by the Linux headers don't match what's used by the `rt_sigaction` system call, so define versions that do.
> Provide `_NSIG`, `kernel_sigset_t`, and `kernel_sigaction`

- gen/modules/general.h
- src/mips/general.rs
- src/mips64/general.rs
- src/riscv32/general.rs
- src/riscv64/general.rs
- src/sparc/general.rs
- src/sparc64/general.rs
riscv and others don't define `SA_RESTORER` and don't have a `sa_restorer` field.
> Don't define the `sa_restorer` field on platforms which lack it.

- src/lib.rs
Following the libc crate which made its `CMSG_*` functions const, make linux-raw-sys's `CMSG_*` functions const.
Some of them can't be with our MSRV of 1.48, so add comments for those.
> Make `CMSG_*` functions const.

- gen/src/main.rs
- src/aarch64/general.rs
- src/aarch64/netlink.rs
- src/arm/general.rs
- src/arm/netlink.rs
- src/mips/general.rs
- src/mips/netlink.rs
- src/mips64/general.rs
- src/mips64/netlink.rs
- src/powerpc/general.rs
- src/powerpc/netlink.rs
- src/powerpc64/general.rs
- src/powerpc64/netlink.rs
- src/riscv32/general.rs
- src/riscv32/netlink.rs
- src/riscv64/general.rs
- src/riscv64/netlink.rs
- src/s390x/general.rs
- src/s390x/netlink.rs
- src/sparc/general.rs
- src/sparc/netlink.rs
- src/sparc64/general.rs
- src/sparc64/netlink.rs
- src/x32/general.rs
- src/x32/netlink.rs
- src/x86/general.rs
- src/x86/netlink.rs
- src/x86_64/general.rs
- src/x86_64/netlink.rs
This eliminates the `size_t` and `ssize_t` types, and uses `usize` and `isize` in their place. This will reduce the amount of casting needed when working with the bindings.
> Enable the `size_t_is_usize` option in bindgen.

- .github/workflows/main.yml
- Cargo.toml
- README.md
- gen/Cargo.toml
- src/lib.rs
This allows us to make a few more functions `const`.
> Update the MSRV to Rust 1.63.

- src/elf.rs
Following up on #78, make the fields of `Elf_auxv_t` public.
> Make `a_type` and `a_val` public fields.

- src/lib.rs
This allows it to match the `CStr` type.
> Change `c_char` to be platform-dependent.

- src/lib.rs
Use the correct `cmsg_len` value when testing for the end of the iteration sequence.
> Fix the definition of `CMSG_NXTHDR`.

- Cargo.toml
Adds missing features to the docs.rs metadata entry in Cargo.toml.
> Add missing features to docs.rs metadata

- Cargo.toml
Docs was missing for new feature `if_packet`.
> Add missing features to docs.rs metadata (#103)

- src/lib.rs
SPARC 32 bit is a tier 3 platform in Rust, though rustix checks against it. A proposed update to 0.6.4 for this library degraded those checks as SPARC 32 bit lacks a definition for `c_char`.
The best evidence I could find as to the signedness of SPARC 32 bit is the blog post linked below, though I have not replicated their findings.
https://github.com/bytecodealliance/rustix/actions/runs/8955815255/job/24596945878?pr=1056 https://trofi.github.io/posts/203-signed-char-or-unsigned-char.html
> Add definition of `c_char` for SPARC

- .github/workflows/main.yml
- Cargo.toml
* Don't warn about `target_arch = "xtensa".
* Update LLVM version.
> Don't warn about `target_arch = "xtensa". (#128)

- gen/modules/net.h
- src/aarch64/net.rs
- src/arm/net.rs
- src/csky/net.rs
- src/loongarch64/net.rs
- src/mips/net.rs
- src/mips32r6/net.rs
- src/mips64/net.rs
- src/mips64r6/net.rs
- src/powerpc/net.rs
- src/powerpc64/net.rs
- src/riscv32/net.rs
- src/riscv64/net.rs
- src/s390x/net.rs
- src/sparc/net.rs
- src/sparc64/net.rs
- src/x32/net.rs
- src/x86/net.rs
- src/x86_64/net.rs
Once this lands I can add `sockopt::set_txtime` to rustix.
> feat: add types from net_tstamp.h, e.g. sock_txtime

- src/lib.rs
This patch sets c_char to signed, same as the legacy MIPS targets. It also matches the fallback definition in the rust core library at `core/src/ffi/primitives.rs`.
> Add c_char definition for MIPS R6
